### ISSUE TITLE
如何安装PyWeChatSpy

### ISSUE THREAD

**Issue by aqc112420** [veikai/PyWeChatSpy#24]
我在Anaconda下想要安装PyWeChatSpy，但是一直安装不上，python=3.8。请问大家是如何安装的呢？谢谢

**Comment by wd1719** [comment]
用pip install 不行？

**Comment by veikai** [comment]
是因为目前pip版本上的SpyHelper.exe的编译方式有问题 git上修复了 暂时没推pip 只需要下载那个SpyHelper.exe替换就可以了

**Comment by DaveISun** [comment]
> 
> 
> 是因为目前pip版本上的SpyHelper.exe的编译方式有问题 git上修复了 暂时没推pip 只需要下载那个SpyHelper.exe替换就可以了

>我刚开始学习python,大佬,能教下怎么安装PyWeChatSpy吗?PyWeChatSpy-master里也没有setup.py,也没找到SpyHelper.exe在哪,麻烦了

**Comment by veikai** [comment]
不需要安装直接运行example.py就行了 就放在项目路径里用

**Comment by DaveISun** [comment]
感谢您的指导,我直接运行了,但是报了如下错误,麻烦帮忙看看

**Comment by DaveISun** [comment]
顺便问下,现在支持微信哪个版本了?
Traceback (most recent call last):
  File "D:/Work/软件/python_lianxi/PyWeChatSpy-master/example.py", line 189, in <module>
    spy = WeChatSpy(response_queue=my_response_queue, key="18d421169d93611a5584affac335e690", logger=logger)
  File "D:\Work\软件\python_lianxi\PyWeChatSpy-master\PyWeChatSpy\spy.py", line 54, in __init__
    subprocess.Popen(helper_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by DaveISun** [comment]
> 
> 
> 不需要安装直接运行example.py就行了 就放在项目路径里用

谢您的指导,我直接运行了,但是报了如下错误,麻烦帮忙看看

**Comment by veikai** [comment]
这就是个文件丢失的错误啊 检查一下静态文件是不是被误删了 微信支持3.0.0.57

**Comment by DaveISun** [comment]
> 
> 
> 这就是个文件丢失的错误啊 检查一下静态文件是不是被误删了 微信支持3.0.0.57

感谢您,我再看看

**Comment by DaveISun** [comment]
> 
> 
> 这就是个文件丢失的错误啊 检查一下静态文件是不是被误删了 微信支持3.0.0.57

可以用了,万分感谢
