### ISSUE TITLE
大佬看下这个报错

### ISSUE THREAD

**Issue by crazypatient0** [veikai/PyWeChatSpy#32]
Traceback (most recent call last):
  File "E:/360/wechat/wechat.py", line 1, in <module>
    from PyWeChatSpy import WeChatSpy
  File "E:\360\wechat\venv\lib\site-packages\PyWeChatSpy\__init__.py", line 1, in <module>
    from .spy import WeChatSpy
  File "E:\360\wechat\venv\lib\site-packages\PyWeChatSpy\spy.py", line 97
    elif not (socket_client := self.__port2client.get(port)):
                            ^
SyntaxError: invalid syntax

**Comment by veikai** [comment]
用python3.8或更高版本
